/**
 * Licensing guidance generator — provides actionable license
 * assessments for each model beyond just "permissive/copyleft".
 * Addresses the legal vacuum Krikorian identifies in his article.
 */

// ── License database ────────────────────────────────────────────────
// Grouped by license type since many models share the same license.

const LICENSE_DB = {
  "Apache-2.0": {
    spdx: "Apache-2.0",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "open",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "Fully permissive. You own your outputs. Attribution required in derivative works. Patent grant included.",
  },
  "MIT": {
    spdx: "MIT",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "open",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "Fully permissive. Minimal restrictions. Include license notice in copies.",
  },
  "Llama-3": {
    spdx: "Llama-3-Community",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: true,
    notableRestrictions: [
      "Monthly active users exceeding 700M require a separate license from Meta",
      'Must include "Built with Llama" in any derivative product',
    ],
    complianceNotes: "Free for commercial use under 700M MAU. Fine-tuning and distillation allowed. Must not use Llama outputs to train competing models.",
  },
  "Llama-2": {
    spdx: "Llama-2-Community",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: true,
    notableRestrictions: [
      "Monthly active users exceeding 700M require a separate license from Meta",
    ],
    complianceNotes: "Free for commercial use under 700M MAU. Superseded by Llama 3 license for newer models.",
  },
  "BigCode-OpenRAIL-M": {
    spdx: "BigCode-OpenRAIL-M",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "open",
    attributionRequired: true,
    notableRestrictions: [
      "Use restrictions: no surveillance, no law enforcement decisions, no medical advice without oversight",
    ],
    complianceNotes: "Permissive with responsible-use restrictions. Commercial use allowed. Training data is from The Stack v2 (opt-out available).",
  },
  "Gemma": {
    spdx: "Gemma-Terms",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: false,
    notableRestrictions: [
      "Cannot use to develop other foundation models (distillation restriction)",
      "Subject to Google Prohibited Use Policy",
    ],
    complianceNotes: "Free for commercial use. Fine-tuning allowed. Cannot use outputs to train competing foundation models.",
  },
  "Mistral-Apache": {
    spdx: "Apache-2.0",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "Apache 2.0 licensed. Fully permissive for commercial use. Training data composition not fully disclosed.",
  },
  "Qwen-Apache": {
    spdx: "Apache-2.0",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "Apache 2.0 licensed. Fully permissive for commercial use. Developed by Alibaba Cloud.",
  },
  "Phi-MIT": {
    spdx: "MIT",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "mixed",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "MIT licensed by Microsoft. Fully permissive. Training data includes synthetic data generated by GPT-4.",
  },
  "WizardCoder-Copyleft": {
    spdx: "BigCode-OpenRAIL-M",
    commercialUse: false,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "mixed",
    attributionRequired: true,
    notableRestrictions: [
      "Built on StarCoder + Evol-Instruct (ChatGPT-generated data)",
      "Commercial use restricted due to mixed training data provenance",
      "OpenAI ToS may apply to portions of training data",
    ],
    complianceNotes: "Copyleft / restricted. Training data includes ChatGPT-generated instructions, creating legal ambiguity for commercial use.",
  },
  "Granite-Apache": {
    spdx: "Apache-2.0",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "open",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "Apache 2.0 by IBM. Enterprise-friendly. Training data is curated and documented. IP indemnification available via IBM watsonx.",
  },
  "DeepSeek": {
    spdx: "MIT",
    commercialUse: true,
    fineTuningAllowed: true,
    outputOwnership: "user",
    trainingDataRights: "undisclosed",
    attributionRequired: true,
    notableRestrictions: [],
    complianceNotes: "MIT licensed. Fully permissive for commercial use. Developed by DeepSeek (China). Training data composition not fully disclosed.",
  },
};

// ── Model → license type mapping ────────────────────────────────────

const MODEL_LICENSE_MAP = {
  "deepseek-coder-v2-16b": "DeepSeek",
  "deepseek-coder-v2-236b": "DeepSeek",
  "deepseek-v3": "DeepSeek",
  "codellama-7b": "Llama-2",
  "codellama-13b": "Llama-2",
  "codellama-34b": "Llama-2",
  "codellama-70b": "Llama-2",
  "starcoder2-3b": "BigCode-OpenRAIL-M",
  "starcoder2-7b": "BigCode-OpenRAIL-M",
  "starcoder2-15b": "BigCode-OpenRAIL-M",
  "llama-3.1-8b": "Llama-3",
  "llama-3.1-70b": "Llama-3",
  "llama-3.1-405b": "Llama-3",
  "llama-3.2-1b": "Llama-3",
  "llama-3.2-3b": "Llama-3",
  "mistral-7b": "Mistral-Apache",
  "mixtral-8x7b": "Mistral-Apache",
  "mixtral-8x22b": "Mistral-Apache",
  "codegemma-2b": "Gemma",
  "codegemma-7b": "Gemma",
  "qwen2.5-coder-1.5b": "Qwen-Apache",
  "qwen2.5-coder-7b": "Qwen-Apache",
  "qwen2.5-coder-14b": "Qwen-Apache",
  "qwen2.5-coder-32b": "Qwen-Apache",
  "phi-3-mini": "Phi-MIT",
  "phi-3-medium": "Phi-MIT",
  "wizardcoder-15b": "WizardCoder-Copyleft",
  "wizardcoder-33b": "WizardCoder-Copyleft",
  "granite-code-3b": "Granite-Apache",
  "granite-code-8b": "Granite-Apache",
  "granite-code-20b": "Granite-Apache",
  "granite-code-34b": "Granite-Apache",
};

// ── Risk assessment ─────────────────────────────────────────────────

function assessRisk(details) {
  if (!details.commercialUse) return "high";
  if (details.notableRestrictions.length > 0) return "medium";
  if (details.trainingDataRights === "undisclosed" || details.trainingDataRights === "mixed") return "medium";
  return "low";
}

function buildSummary(details, riskLevel) {
  if (riskLevel === "low") return "Safe for commercial use — fully permissive license";
  if (!details.commercialUse) return "Commercial use restricted — review license before shipping";
  if (details.notableRestrictions.length > 0) return "Commercial use allowed with conditions — review restrictions";
  return "Commercial use likely OK — some data provenance concerns";
}

function buildActionItems(details) {
  const items = [];
  if (!details.commercialUse) {
    items.push("Do NOT use in commercial products without legal review");
  }
  for (const restriction of details.notableRestrictions) {
    items.push(`Review: ${restriction}`);
  }
  if (details.trainingDataRights === "undisclosed") {
    items.push("Training data provenance is not fully disclosed — assess risk for your compliance requirements");
  }
  if (details.trainingDataRights === "mixed") {
    items.push("Training data includes mixed sources — verify compliance with your data governance policies");
  }
  return items;
}

// ── Main generator ──────────────────────────────────────────────────

export function generateLicenseGuidance(model) {
  const licenseType = MODEL_LICENSE_MAP[model.id];
  const details = licenseType ? LICENSE_DB[licenseType] : null;

  if (!details) {
    return {
      summary: "License information unavailable",
      riskLevel: "medium",
      details: null,
      actionItems: ["Verify license terms before commercial use"],
      disclaimer: "This is informational guidance, not legal advice.",
    };
  }

  const riskLevel = assessRisk(details);
  const summary = buildSummary(details, riskLevel);
  const actionItems = buildActionItems(details);

  return {
    summary,
    riskLevel,
    details: {
      spdx: details.spdx,
      commercialUse: { allowed: details.commercialUse, note: details.complianceNotes },
      fineTuning: { allowed: details.fineTuningAllowed, note: details.fineTuningAllowed ? "Fine-tuning and LoRA adapters permitted" : "Fine-tuning restricted" },
      outputOwnership: { status: details.outputOwnership, note: details.outputOwnership === "user" ? "You own all generated outputs" : "Review output ownership terms" },
      trainingData: { status: details.trainingDataRights, note: details.trainingDataRights === "open" ? "Training data is documented and auditable" : details.trainingDataRights === "undisclosed" ? "Training data composition not fully disclosed" : "Training data includes mixed sources" },
      attribution: { required: details.attributionRequired, note: details.attributionRequired ? "Include license/attribution notice in derivative works" : "No attribution required" },
    },
    actionItems,
    disclaimer: "This is informational guidance, not legal advice. Consult a lawyer for compliance decisions.",
  };
}
