// Comprehensive database of open LLMs for developers.
// All benchmark numbers, RAM requirements, and specs are realistic estimates
// based on publicly available information as of early 2025.

export const MODELS = [
  // ── DeepSeek Coder V2 ──────────────────────────────────────────────
  {
    id: "deepseek-coder-v2-16b",
    name: "DeepSeek Coder V2 Lite",
    family: "DeepSeek Coder V2",
    params: "16B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "instruction-following", "math", "reasoning", "fill-in-middle"],
    weaknesses: ["multilingual-prose", "creative-writing"],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 73.8, swebench: 15.2, aiderPolyglot: 18.4 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-06-17",
    provider: "DeepSeek",
    url: "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct",
  },
  {
    id: "deepseek-coder-v2-236b",
    name: "DeepSeek Coder V2",
    family: "DeepSeek Coder V2",
    params: "236B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "reasoning", "math", "instruction-following", "fill-in-middle", "architecture"],
    weaknesses: ["compute-heavy"],
    minRAM: "128GB",
    typicalLatency: "high",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["vllm", "huggingface"],
    deploymentOptions: ["cloud"],
    benchmarks: { humaneval: 90.2, swebench: 22.6, aiderPolyglot: 35.1 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-06-17",
    provider: "DeepSeek",
    url: "https://huggingface.co/deepseek-ai/DeepSeek-Coder-V2-Instruct",
  },

  // ── DeepSeek V3 ────────────────────────────────────────────────────
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    family: "DeepSeek V3",
    params: "671B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "reasoning", "math", "instruction-following", "multilingual", "architecture"],
    weaknesses: ["compute-heavy", "high-memory"],
    minRAM: "256GB",
    typicalLatency: "high",
    fineTunable: false,
    adapterSupport: false,
    ecosystem: ["vllm", "huggingface"],
    deploymentOptions: ["cloud"],
    benchmarks: { humaneval: 91.6, swebench: 26.8, aiderPolyglot: 49.6 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-12-26",
    provider: "DeepSeek",
    url: "https://huggingface.co/deepseek-ai/DeepSeek-V3",
  },

  // ── CodeLlama ──────────────────────────────────────────────────────
  {
    id: "codellama-7b",
    name: "CodeLlama 7B",
    family: "CodeLlama",
    params: "7B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "instruction-following"],
    weaknesses: ["reasoning", "architecture", "multilingual"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 33.5, swebench: 2.1, aiderPolyglot: 5.8 },
    defaultConfig: { temperature: 0.1, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2023-08-24",
    provider: "Meta",
    url: "https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf",
  },
  {
    id: "codellama-13b",
    name: "CodeLlama 13B",
    family: "CodeLlama",
    params: "13B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "instruction-following"],
    weaknesses: ["reasoning", "architecture", "multilingual"],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 36.0, swebench: 3.4, aiderPolyglot: 7.2 },
    defaultConfig: { temperature: 0.1, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2023-08-24",
    provider: "Meta",
    url: "https://huggingface.co/codellama/CodeLlama-13b-Instruct-hf",
  },
  {
    id: "codellama-34b",
    name: "CodeLlama 34B",
    family: "CodeLlama",
    params: "34B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "reasoning", "instruction-following"],
    weaknesses: ["architecture", "multilingual"],
    minRAM: "32GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 48.8, swebench: 6.2, aiderPolyglot: 11.5 },
    defaultConfig: { temperature: 0.1, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2023-08-24",
    provider: "Meta",
    url: "https://huggingface.co/codellama/CodeLlama-34b-Instruct-hf",
  },
  {
    id: "codellama-70b",
    name: "CodeLlama 70B",
    family: "CodeLlama",
    params: "70B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "reasoning", "instruction-following"],
    weaknesses: ["architecture", "multilingual", "compute-heavy"],
    minRAM: "64GB",
    typicalLatency: "high",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["vllm", "huggingface", "llama.cpp"],
    deploymentOptions: ["cloud", "hybrid"],
    benchmarks: { humaneval: 53.0, swebench: 8.5, aiderPolyglot: 14.3 },
    defaultConfig: { temperature: 0.1, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-01-29",
    provider: "Meta",
    url: "https://huggingface.co/codellama/CodeLlama-70b-Instruct-hf",
  },

  // ── StarCoder2 ─────────────────────────────────────────────────────
  {
    id: "starcoder2-3b",
    name: "StarCoder2 3B",
    family: "StarCoder2",
    params: "3B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "multilingual"],
    weaknesses: ["reasoning", "instruction-following", "architecture"],
    minRAM: "4GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 31.7, swebench: 1.8, aiderPolyglot: 4.9 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-02-28",
    provider: "BigCode",
    url: "https://huggingface.co/bigcode/starcoder2-3b",
  },
  {
    id: "starcoder2-7b",
    name: "StarCoder2 7B",
    family: "StarCoder2",
    params: "7B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "multilingual"],
    weaknesses: ["reasoning", "instruction-following", "architecture"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 35.4, swebench: 2.5, aiderPolyglot: 6.4 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-02-28",
    provider: "BigCode",
    url: "https://huggingface.co/bigcode/starcoder2-7b",
  },
  {
    id: "starcoder2-15b",
    name: "StarCoder2 15B",
    family: "StarCoder2",
    params: "15B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "multilingual"],
    weaknesses: ["reasoning", "architecture"],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 46.3, swebench: 5.1, aiderPolyglot: 9.7 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-02-28",
    provider: "BigCode",
    url: "https://huggingface.co/bigcode/starcoder2-15b",
  },

  // ── Llama 3.1 ──────────────────────────────────────────────────────
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B Instruct",
    family: "Llama 3.1",
    params: "8B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "multilingual", "codegen"],
    weaknesses: ["specialized-code-tasks"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 62.2, swebench: 10.1, aiderPolyglot: 15.6 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-07-23",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Meta-Llama-3.1-8B-Instruct",
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B Instruct",
    family: "Llama 3.1",
    params: "70B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "multilingual", "codegen", "architecture", "math"],
    weaknesses: ["compute-heavy"],
    minRAM: "64GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["cloud", "hybrid"],
    benchmarks: { humaneval: 80.5, swebench: 18.3, aiderPolyglot: 30.2 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-07-23",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Meta-Llama-3.1-70B-Instruct",
  },
  {
    id: "llama-3.1-405b",
    name: "Llama 3.1 405B Instruct",
    family: "Llama 3.1",
    params: "405B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "multilingual", "codegen", "architecture", "math"],
    weaknesses: ["compute-heavy", "high-memory"],
    minRAM: "256GB",
    typicalLatency: "high",
    fineTunable: false,
    adapterSupport: false,
    ecosystem: ["vllm", "huggingface"],
    deploymentOptions: ["cloud"],
    benchmarks: { humaneval: 89.0, swebench: 23.1, aiderPolyglot: 40.5 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-07-23",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Meta-Llama-3.1-405B-Instruct",
  },

  // ── Llama 3.2 (small/on-device) ───────────────────────────────────
  {
    id: "llama-3.2-1b",
    name: "Llama 3.2 1B Instruct",
    family: "Llama 3.2",
    params: "1B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "on-device", "low-latency"],
    weaknesses: ["codegen", "reasoning", "architecture"],
    minRAM: "2GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "hybrid"],
    benchmarks: { humaneval: 14.6, swebench: null, aiderPolyglot: 1.2 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 2048 },
    releaseDate: "2024-09-25",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct",
  },
  {
    id: "llama-3.2-3b",
    name: "Llama 3.2 3B Instruct",
    family: "Llama 3.2",
    params: "3B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "on-device", "low-latency", "codegen"],
    weaknesses: ["reasoning", "architecture"],
    minRAM: "4GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "hybrid"],
    benchmarks: { humaneval: 25.6, swebench: 1.4, aiderPolyglot: 3.8 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 2048 },
    releaseDate: "2024-09-25",
    provider: "Meta",
    url: "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
  },

  // ── Mistral / Mixtral ──────────────────────────────────────────────
  {
    id: "mistral-7b",
    name: "Mistral 7B Instruct v0.3",
    family: "Mistral",
    params: "7B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "codegen", "multilingual"],
    weaknesses: ["specialized-code-tasks", "architecture"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 40.2, swebench: 4.8, aiderPolyglot: 9.1 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-05-22",
    provider: "Mistral AI",
    url: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3",
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B Instruct",
    family: "Mixtral",
    params: "46.7B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "codegen", "multilingual", "math"],
    weaknesses: ["memory-footprint"],
    minRAM: "48GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["cloud", "hybrid"],
    benchmarks: { humaneval: 45.1, swebench: 7.2, aiderPolyglot: 12.8 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-01-08",
    provider: "Mistral AI",
    url: "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1",
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8x22B Instruct",
    family: "Mixtral",
    params: "141B",
    contextWindow: 65_536,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["instruction-following", "reasoning", "codegen", "multilingual", "math", "architecture"],
    weaknesses: ["compute-heavy", "high-memory"],
    minRAM: "128GB",
    typicalLatency: "high",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["vllm", "huggingface"],
    deploymentOptions: ["cloud"],
    benchmarks: { humaneval: 55.8, swebench: 10.4, aiderPolyglot: 18.9 },
    defaultConfig: { temperature: 0.1, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-04-17",
    provider: "Mistral AI",
    url: "https://huggingface.co/mistralai/Mixtral-8x22B-Instruct-v0.1",
  },

  // ── CodeGemma ──────────────────────────────────────────────────────
  {
    id: "codegemma-2b",
    name: "CodeGemma 2B",
    family: "CodeGemma",
    params: "2B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "on-device"],
    weaknesses: ["reasoning", "instruction-following", "architecture", "multilingual"],
    minRAM: "4GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "hybrid"],
    benchmarks: { humaneval: 31.1, swebench: null, aiderPolyglot: 3.2 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-04-09",
    provider: "Google",
    url: "https://huggingface.co/google/codegemma-2b",
  },
  {
    id: "codegemma-7b",
    name: "CodeGemma 7B Instruct",
    family: "CodeGemma",
    params: "7B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "fill-in-middle", "instruction-following"],
    weaknesses: ["reasoning", "architecture", "multilingual"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 44.4, swebench: 4.2, aiderPolyglot: 8.1 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-04-09",
    provider: "Google",
    url: "https://huggingface.co/google/codegemma-7b-it",
  },

  // ── Qwen2.5-Coder ─────────────────────────────────────────────────
  {
    id: "qwen2.5-coder-1.5b",
    name: "Qwen2.5-Coder 1.5B Instruct",
    family: "Qwen2.5-Coder",
    params: "1.5B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "on-device", "low-latency", "multilingual"],
    weaknesses: ["reasoning", "architecture"],
    minRAM: "2GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "hybrid"],
    benchmarks: { humaneval: 43.6, swebench: 2.8, aiderPolyglot: 5.5 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-11-11",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct",
  },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen2.5-Coder 7B Instruct",
    family: "Qwen2.5-Coder",
    params: "7B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "instruction-following", "multilingual", "reasoning"],
    weaknesses: ["architecture"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 70.4, swebench: 12.5, aiderPolyglot: 18.2 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-11-11",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-Coder-7B-Instruct",
  },
  {
    id: "qwen2.5-coder-14b",
    name: "Qwen2.5-Coder 14B Instruct",
    family: "Qwen2.5-Coder",
    params: "14B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "instruction-following", "reasoning", "multilingual", "math"],
    weaknesses: [],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 78.2, swebench: 16.8, aiderPolyglot: 24.6 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-11-11",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-Coder-14B-Instruct",
  },
  {
    id: "qwen2.5-coder-32b",
    name: "Qwen2.5-Coder 32B Instruct",
    family: "Qwen2.5-Coder",
    params: "32B",
    contextWindow: 32_768,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "instruction-following", "reasoning", "multilingual", "math", "architecture"],
    weaknesses: [],
    minRAM: "32GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 92.7, swebench: 21.4, aiderPolyglot: 33.8 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 4096 },
    releaseDate: "2024-11-11",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-Coder-32B-Instruct",
  },

  // ── Phi-3 ──────────────────────────────────────────────────────────
  {
    id: "phi-3-mini",
    name: "Phi-3 Mini (3.8B)",
    family: "Phi-3",
    params: "3.8B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["reasoning", "math", "codegen", "on-device", "instruction-following"],
    weaknesses: ["multilingual", "architecture"],
    minRAM: "4GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 58.5, swebench: 5.6, aiderPolyglot: 8.9 },
    defaultConfig: { temperature: 0.0, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-04-23",
    provider: "Microsoft",
    url: "https://huggingface.co/microsoft/Phi-3-mini-128k-instruct",
  },
  {
    id: "phi-3-medium",
    name: "Phi-3 Medium (14B)",
    family: "Phi-3",
    params: "14B",
    contextWindow: 128_000,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["reasoning", "math", "codegen", "instruction-following", "multilingual"],
    weaknesses: ["architecture"],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 62.8, swebench: 8.9, aiderPolyglot: 14.2 },
    defaultConfig: { temperature: 0.0, topP: 0.9, maxTokens: 4096 },
    releaseDate: "2024-05-21",
    provider: "Microsoft",
    url: "https://huggingface.co/microsoft/Phi-3-medium-128k-instruct",
  },

  // ── WizardCoder ────────────────────────────────────────────────────
  {
    id: "wizardcoder-15b",
    name: "WizardCoder 15B V1.0",
    family: "WizardCoder",
    params: "15B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: true,
    license: "copyleft",
    commercialUse: false,
    strengths: ["codegen", "instruction-following"],
    weaknesses: ["reasoning", "architecture", "multilingual", "outdated"],
    minRAM: "16GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 57.3, swebench: 4.1, aiderPolyglot: 7.8 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2023-06-14",
    provider: "WizardLM",
    url: "https://huggingface.co/WizardLM/WizardCoder-15B-V1.0",
  },
  {
    id: "wizardcoder-33b",
    name: "WizardCoder 33B V1.1",
    family: "WizardCoder",
    params: "33B",
    contextWindow: 16_384,
    quantizable: true,
    onDevice: false,
    license: "copyleft",
    commercialUse: false,
    strengths: ["codegen", "instruction-following", "reasoning"],
    weaknesses: ["architecture", "multilingual", "outdated"],
    minRAM: "32GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 79.9, swebench: 7.8, aiderPolyglot: 13.5 },
    defaultConfig: { temperature: 0.0, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2023-11-09",
    provider: "WizardLM",
    url: "https://huggingface.co/WizardLM/WizardCoder-33B-V1.1",
  },

  // ── Granite Code ───────────────────────────────────────────────────
  {
    id: "granite-code-3b",
    name: "Granite Code 3B Instruct",
    family: "Granite Code",
    params: "3B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "on-device", "enterprise", "multilingual"],
    weaknesses: ["reasoning", "architecture"],
    minRAM: "4GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 28.0, swebench: 1.5, aiderPolyglot: 3.9 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-05-06",
    provider: "IBM",
    url: "https://huggingface.co/ibm-granite/granite-3b-code-instruct",
  },
  {
    id: "granite-code-8b",
    name: "Granite Code 8B Instruct",
    family: "Granite Code",
    params: "8B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: true,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "enterprise", "multilingual", "instruction-following"],
    weaknesses: ["reasoning", "architecture"],
    minRAM: "8GB",
    typicalLatency: "low",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 42.7, swebench: 4.8, aiderPolyglot: 8.3 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-05-06",
    provider: "IBM",
    url: "https://huggingface.co/ibm-granite/granite-8b-code-instruct",
  },
  {
    id: "granite-code-20b",
    name: "Granite Code 20B Instruct",
    family: "Granite Code",
    params: "20B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "enterprise", "multilingual", "instruction-following", "reasoning"],
    weaknesses: ["architecture"],
    minRAM: "24GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 52.4, swebench: 7.1, aiderPolyglot: 12.0 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-05-06",
    provider: "IBM",
    url: "https://huggingface.co/ibm-granite/granite-20b-code-instruct",
  },
  {
    id: "granite-code-34b",
    name: "Granite Code 34B Instruct",
    family: "Granite Code",
    params: "34B",
    contextWindow: 8_192,
    quantizable: true,
    onDevice: false,
    license: "permissive",
    commercialUse: true,
    strengths: ["codegen", "enterprise", "multilingual", "instruction-following", "reasoning"],
    weaknesses: ["architecture", "context-window-small"],
    minRAM: "32GB",
    typicalLatency: "medium",
    fineTunable: true,
    adapterSupport: true,
    ecosystem: ["ollama", "llama.cpp", "vllm", "huggingface", "lm-studio"],
    deploymentOptions: ["local", "cloud", "hybrid"],
    benchmarks: { humaneval: 58.1, swebench: 9.2, aiderPolyglot: 14.7 },
    defaultConfig: { temperature: 0.2, topP: 0.95, maxTokens: 2048 },
    releaseDate: "2024-05-06",
    provider: "IBM",
    url: "https://huggingface.co/ibm-granite/granite-34b-code-instruct",
  },
];

// Helper: parse "8GB" → 8, "256GB" → 256
export function parseMemGB(memStr) {
  if (!memStr) return Infinity;
  const match = memStr.match(/^(\d+)/);
  return match ? parseInt(match[1], 10) : Infinity;
}

// Helper: get all unique families
export function getModelFamilies() {
  return [...new Set(MODELS.map((m) => m.family))];
}

// Helper: find model by id
export function getModelById(id) {
  return MODELS.find((m) => m.id === id) || null;
}
